const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('api', {
  browseDir:          ()           => ipcRenderer.invoke('browse-dir'),
  browseRepoDir:      ()           => ipcRenderer.invoke('browse-repo-dir'),
  getRepoDir:         ()           => ipcRenderer.invoke('get-repo-dir'),
  setRepoDir:         (dir)        => ipcRenderer.invoke('set-repo-dir', dir),
  saveSetting:        (k, v)       => ipcRenderer.invoke('save-setting', k, v),
  loadSettings:       ()           => ipcRenderer.invoke('load-settings'),
  getRepoMods:        ()           => ipcRenderer.invoke('get-repo-mods'),
  getInstalledPak:    (dir)        => ipcRenderer.invoke('get-installed-pak', dir),
  getInstalledLua:    (dir)        => ipcRenderer.invoke('get-installed-lua', dir),
  checkUe4ss:         (dir)        => ipcRenderer.invoke('check-ue4ss', dir),
  installUe4ss:       (dir, name)  => ipcRenderer.invoke('install-ue4ss', dir, name),
  downloadZip:        (url, icon, name, pageUrl) => ipcRenderer.invoke('download-zip', url, icon || '', name || '', pageUrl || ''),
  checkModUpdates:    () => ipcRenderer.invoke('check-mod-updates'),
  checkAppUpdate:     () => ipcRenderer.invoke('check-app-update'),
  getAppVersion:      () => ipcRenderer.invoke('get-app-version'),
  installAppUpdate:   (url, name) => ipcRenderer.invoke('install-app-update', url, name),
  installMod:         (name, dir, targetType)    => ipcRenderer.invoke('install-mod', name, dir, targetType || null),
  installModSelected: (name, dir, files, targetType) => ipcRenderer.invoke('install-mod-selected', name, dir, files, targetType || 'pak'),
  detectPakVariants:  (name)                     => ipcRenderer.invoke('detect-pak-variants', name),
  listArchiveContents:(name, targetType, variant) => ipcRenderer.invoke('list-archive-contents', name, targetType || 'pak', variant || null),
  deleteInstalledPak: (name, dir)  => ipcRenderer.invoke('delete-installed-pak', name, dir),
  deleteInstalledLua: (name, dir)  => ipcRenderer.invoke('delete-installed-lua', name, dir),
  deleteRepoMod:      (zip)        => ipcRenderer.invoke('delete-repo-mod', zip),
  validateGameDir:    (dir)        => ipcRenderer.invoke('validate-game-dir', dir),
  fetchImage:         (url)        => ipcRenderer.invoke('fetch-image', url),
  openExternal:       (url)        => ipcRenderer.invoke('open-external', url),
  getFeaturedMod:     ()           => ipcRenderer.invoke('get-featured-mod'),
  getMyMods:          ()           => ipcRenderer.invoke('get-my-mods'),
  openRepoDir:        ()           => ipcRenderer.invoke('open-repo-dir'),
  openPath:           (p)          => ipcRenderer.invoke('open-path', p),
  deletePath:         (p)          => ipcRenderer.invoke('delete-path', p),
  getFolderContents:  (p)          => ipcRenderer.invoke('get-folder-contents', p),
  checkLogin:         ()           => ipcRenderer.invoke('check-login'),
  loginOvertake:      ()           => ipcRenderer.invoke('login-overtake'),
  logoutOvertake:     ()           => ipcRenderer.invoke('logout-overtake'),
  scrapeOvertake:     (page)       => ipcRenderer.invoke('scrape-overtake', page || 1),
  searchOvertake:     (query)      => ipcRenderer.invoke('search-overtake', query),
  buildModCache:      ()           => ipcRenderer.invoke('build-mod-cache'),
  getCacheStatus:     ()           => ipcRenderer.invoke('get-cache-status'),
  onCacheProgress:    (cb)         => ipcRenderer.on('cache-progress', (_, data) => cb(data)),
  onScrapeProgress:   (cb)         => ipcRenderer.on('scrape-progress', (_, data) => cb(data)),
  onInstallProgress:  (cb)         => ipcRenderer.on('install-progress', (_, data) => cb(data)),
  offInstallProgress: ()           => ipcRenderer.removeAllListeners('install-progress'),
  launchGame:         (dir)        => ipcRenderer.invoke('launch-game', dir),
  importModFile:      (filePath)   => ipcRenderer.invoke('import-mod-file', filePath),
  onUe4ssProgress:    (cb) => ipcRenderer.on('ue4ss-install-progress', (_, d) => cb(d)),
  offUe4ssProgress:   ()  => ipcRenderer.removeAllListeners('ue4ss-install-progress'),
  onDownloadProgress: (cb) => ipcRenderer.on('download-progress', (_, d) => cb(d)),
  offDownloadProgress:()  => ipcRenderer.removeAllListeners('download-progress'),
  getPathForFile:     (file) => webUtils.getPathForFile(file),
});
